### ISSUE TITLE
Use of ExecutorService creates non-daemon threads

### ISSUE THREAD

**Issue by robross0606** [deepsidhu1313/SyntaxTextAreaFX#4]
Your use of ExecutorService in SyntaxTextAreaFX constructor creates a non-daemon thread that does not shut down when the window closes.  So this:

>
        executor = Executors.newSingleThreadExecutor();

Should be something like this:

> 
        executor = Executors.newSingleThreadExecutor(runnable -> {
            Thread thread = Executors.defaultThreadFactory().newThread(runnable);
            thread.setDaemon(true);
            return thread;
        });

**Comment by deepsidhu1313** [comment]
Completely agree with you. 

Consider me newbie, can you explain your new code ??

**Comment by robross0606** [comment]
The executor service allows you to pass in a ThreadFactory instance 
which is used to create threads when the ExecutorService requires them.  
This change simply creates a ThreadFactory that creates threads and then 
sets them as daemon threads.  A daemon thread will shut down 
automatically (and immediately) when the parent thread is closed.

------ Original Message ------

**Comment by deepsidhu1313** [comment]
Thanks for the code. Committed the changes. We can close this issue if you want.
