### ISSUE TITLE
Add support for Apache Groovy language

### ISSUE THREAD

**Issue by dustinkredmond** [deepsidhu1313/SyntaxTextAreaFX#7]
Really love this project. I would like to see support for the Apache Groovy language. If anyone else is interested, I may be able to add this, pending availability. There's a few things to look out for ex. the triple-quote multi-line string
```groovy
def someString = """
  This is a string
  spanning multiple lines
"""
```

Also, highlighting for String interpolation

```groovy
def year = LocalDate.now().getYear()
def someString = "The year was ${year}"
```

**Comment by deepsidhu1313** [comment]
@dustinkredmond my apologies, i am not actively working on this project, but please feel free to fork the code and/or create MRs.
